// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5jxcI0Dle0iN5pJY-aqw8j7qtZVyiE1M',
    appId: '1:69565275356:web:cac02b8c53cf869df12819',
    messagingSenderId: '69565275356',
    projectId: 'smartlock-25056',
    authDomain: 'smartlock-25056.firebaseapp.com',
    databaseURL: 'https://smartlock-25056-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartlock-25056.firebasestorage.app',
    measurementId: 'G-P81020EY5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKK3RKqFsW_tM6Nt7putuwnVzRSDXvkH0',
    appId: '1:69565275356:android:6ee9d1d8a381323bf12819',
    messagingSenderId: '69565275356',
    projectId: 'smartlock-25056',
    databaseURL: 'https://smartlock-25056-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartlock-25056.firebasestorage.app',
  );
}
